config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root 'pages#home'
  devise_for :users,
              path: '',
              path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  
  resources :users, only: [:show]

  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
    end

    resources :photos, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :capacity, presence: true
  validates :bedroom_count, presence: true
  validates :bathroom_count, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :omniauthable

  validates :fullname, presence: true, length: { maximum: 50 }

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.fullname = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image
        user.uid = auth.uid
        user.provider = auth.provider
        # If you are using confirmable and the provider(s) you use validate emails, 
        # uncomment the line below to skip the confirmation emails.
        user.skip_confirmation!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :phone_number, :description])
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @room = Room.find(params[:room_id])

    if params[:images]
      params[:images].each do |img|
        @room.photos.create(image: img)
      end

      @photos = @room.photos
      redirect_back(fallback_location: request.referer, notice: "Saved...")
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
    def update_resource(resource, params)
      resource.update_without_password(params)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorized, only: [:listing, :pricing, :description, 
                                      :photo_upload, :amenities, :location, :update]

  def index
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved..."
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def show
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def is_authorized
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :capacity, :bedroom_count, :bathroom_count, :listing_name, :description, :address, :has_tv, :has_kitchen, :has_aircon, :has_heating, :has_internet, :price, :active)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    if user.image
      "http://graph.facebook.com/#{user.uid}/picture?type=large"
    else
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "https://secure.gravatar.com/avatar/#{gravatar_id}.jpg?s=250"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Sunbnb</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render "shared/header" %>

        <%= render "shared/message" %>

        <div class="container mt-5">
            <%= yield %>
        </div>
    </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/_photo_list.html.erb
<% if @photos.count > 0 %>
    <br><br>

    <div class="row">
        <% @photos.each do |photo| %>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header preview">
                        <%= image_tag photo.image.url %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
<% end %>

app/views/rooms/_sidebar.html.erb
<ul class="sidebar-list">
    <li class="sidebar-item">
        <%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
    </li>

    <li class="sidebar-item">
        <%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
    </li>

    <li class="sidebar-item">
        <%= link_to "Description", description_room_path, class: "sidebar-link active" %>
    </li>

    <li class="sidebar-item">
        <%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %>
    </li>

    <li class="sidebar-item">
        <%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
    </li>

    <li class="sidebar-item">
        <%= link_to "Location", location_room_path, class: "sidebar-link active" %>
    </li>
</ul>

app/views/rooms/amenities.html.erb
<div class="row">
    <div class="col-md-3">
        <%= render "sidebar" %>
    </div>

    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                Amenities
            </div>

            <div class="card-body">
                <div class="container">
                    <%= form_for @room do |f| %>
                        <div class="row form-group">
                            <div class="col-md-4">
                                <%= f.check_box :has_tv %> TV
                            </div>

                            <div class="col-md-4">
                                <%= f.check_box :has_kitchen %> Kitchen
                            </div>

                            <div class="col-md-4">
                                <%= f.check_box :has_internet %> Internet
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-md-4">
                                <%= f.check_box :has_heating %> Heating
                            </div>

                            <div class="col-md-4">
                                <%= f.check_box :has_aircon %> Air Conditioning
                            </div>
                        </div>
                        <br/><br/>

                        <div class="text-center">
                            <%= f.submit "Save", class: "btn btn-form" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/description.html.erb
<div class="row">
    <div class="col-md-3">
        <%= render "sidebar" %>
    </div>

    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                Description
            </div>

            <div class="card-body">
                <div class="container">
                    <%= form_for @room do |f| %>
                        <div class="form-group">
                            <label>Listing name</label>
                            <%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
                        </div>

                        <div class="form-group">
                            <label>Summary</label>
                            <%= f.text_area :description, rows: 5, placeholder: "Summary of your house", class: "form-control", required: true %>
                        </div>

                        <div class="text-center">
                            <%= f.submit "Save", class: "btn btn-form" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>

app/views/rooms/listing.html.erb
<div class="row">
    <div class="col-md-3">
        <%= render "sidebar" %>
    </div>

    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                Listing
            </div>

            <div class="card-body">
                <div class="container">
                    <%= form_for @room do |f| %>
                        <div class="row">
                            <div class="col-md-4 select">
                                <div class="form-group">
                                    <label>Home Type</label>
                                    <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                                                id: "home_type", prompt: "Select...", class: "form-control" %>
                                </div>
                            </div>

                            <div class="col-md-4 select">
                                <div class="form-group">
                                    <label>Room Type</label>
                                    <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                                                id: "room_type", prompt: "Select...", class: "form-control" %>
                                </div>
                            </div>

                            <div class="col-md-4 select">
                                <div class="form-group">
                                    <label>Accommodate</label>
                                    <%= f.select :capacity, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                                id: "capacity", prompt: "Select...", class: "form-control" %>
                                </div>
                            </div>

                            <div class="col-md-4 select">
                                <div class="form-group">
                                    <label>Bedrooms</label>
                                    <%= f.select :bedroom_count, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                                id: "bedroom_count", prompt: "Select...", class: "form-control" %>
                                </div>
                            </div>

                            <div class="col-md-4 select">
                                <div class="form-group">
                                    <label>Bathrooms</label>
                                    <%= f.select :bathroom_count, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                                id: "bathroom_count", prompt: "Select...", class: "form-control" %>
                                </div>
                            </div>
                        </div>

                        <div><%= f.submit "Save", class: "btn btn-normal" %></div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
    <div class="col-md-3">
        <%= render "sidebar" %>
    </div>

    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                Location
            </div>

            <div class="card-body">
                <div class="container">
                    <%= form_for @room do |f| %>

                        <div class="form-group">
                            <label>Address</label>
                            <%= f.text_field :address, placeholder: "What is your address?", class: "form-control", required: true %>
                        </div>

                        <div class="text-center">
                            <%= f.submit "Save", class: "btn btn-form" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/new.html.erb
<div class="card">
    <div class="card-header">
        Create your beautiful place
    </div>
    <div class="card-body">
        <div class="container">
            <%= form_for @room do |f| %>
                <div class="row">
                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Home Type</label>
                            <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                                        id: "home_type", prompt: "Select...", class: "form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Room Type</label>
                            <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                                        id: "room_type", prompt: "Select...", class: "form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Accommodate</label>
                            <%= f.select :capacity, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                        id: "capacity", prompt: "Select...", class: "form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Bedrooms</label>
                            <%= f.select :bedroom_count, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                        id: "bedroom_count", prompt: "Select...", class: "form-control" %>
                        </div>
                    </div>

                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Bathrooms</label>
                            <%= f.select :bathroom_count, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                        id: "bathroom_count", prompt: "Select...", class: "form-control" %>
                        </div>
                    </div>
                </div>

                <div><%= f.submit "Create My Room", class: "btn btn-normal" %></div>
            <% end %>
        </div>
    </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
    <div class="col-md-3">
        <%= render "sidebar" %>
    </div>

    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                Photos
            </div>

            <div class="card-body">
                <div class="container">
                    <div class="row">
                        <div class="offset-md-3 col-md-6">
                            <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                                <div class="form-group">
                                    <span class="btn btn-default btn-file teal">
                                        <i class="fa fa-cloud-upload"></i> Select Photos
                                        <%= file_field_tag "images[]", type: :file, multiple: true %>
                                    </span>
                                </div>

                                <div class="text-center">
                                    <%= f.submit "Add Photos", class: "btn btn-form" %>
                                </div>
                            <% end %>
                        </div>
                    </div>

                    <div id="photos"><%= render "photos/photo_list" %></div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
    <div class="col-md-3">
        <%= render "sidebar" %>
    </div>

    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                Pricing
            </div>

            <div class="card-body">
                <div class="container">
                    <%= form_for @room do |f| %>
                        <div class="form-group">
                            <label>Price</label>
                            <%= f.text_field :price, placeholder: "eg: $100", class: "form-control", required: true %>
                        </div>

                        <div class="text-center">
                            <%= f.submit "Save", class: "btn btn-form" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rooms/show.html.erb
<h1>Rooms#show</h1>
<p>Find me in app/views/rooms/show.html.erb</p>

app/views/shared/_devise_messages.html.erb
<% unless resource.errors.empty? %>
    <script type="text/javascript">
        <% resource.errors.full_messages.each do |value| %>
            toastr.error('<%= value %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-expand-lg navbar-default bg-white rounded">
    <div class="container">
        <%= link_to "sunbnb", root_path, class: "navbar-brand" %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
            <ul class="navbar-nav ml-auto justify-content-end">
                <% if (!user_signed_in?) %>
                    <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
                    <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
                <% else %>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown09" 
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= image_tag avatar_url(current_user), class: "rounded-circle avatar-small" %>&nbsp;
                            <%= current_user.fullname %>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdown09">
                            <%= link_to "Manage Listing", "#", class: "dropdown-item" %>
                            <%= link_to "List Your Space", new_room_path, class: "dropdown-item" %>
                            <%= link_to "Your Reservations", "#", class: "dropdown-item" %>
                            <%= link_to "Your Trips", "#", class: "dropdown-item" %>
                            <div class="dropdown-divider"></div>
                            <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                        </div>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav> 

app/views/shared/_message.html.erb
<% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |key, value| %>
            <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
            toastr['<%= type %>']('<%= value %>')
        <% end %>
    </script>
<% end %> 

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-3">
        <div class="center">
            <%= image_tag avatar_url(@user), class: "avatar-full" %>
        </div>
        <div class="card">
            <div class="card-header">Verification</div>
            <div class="card-body">
                <ul class="sidebar-list">
                    <% if @user.confirmation_token %>
                        <li>Email Address<span class="pull-right teal"><i class="fa fa-check-circle-o"></i></span></li>
                    <% end %>
                    <% if @user.provider %>
                        <li>Facebook<span class="pull-right teal"><i class="fa fa-check-circle-o"></i></span></li>
                    <% end %>
                    <% if @user.phone_number %>
                        <li>Phone Number<span class="pull-right teal"><i class="fa fa-check-circle-o"></i></span></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-md-9">
        <h2><%= @user.fullname %></h2>

        <div class="description row-space-3">
            <%= @user.description %>
        </div>
    </div>
</div>